// Turn a natural-language query into per-platform optimized queries.
// Ported from backend/ai_logic.py — Groq only (Gemini fallback dropped;
// rule-based fallback preserved for the no-key case).

import {
  callGroq,
  corsPreflight,
  jsonResponse,
  resolveGroqKey,
  sanitizeQuery,
} from "../_shared/groq";

interface OptimizeResponse {
  github_query: string;
  huggingface_query: string;
  reddit_query: string;
  intent?: string;
  source_weights?: Record<string, number>;
  reasoning?: string;
}

export const onRequestOptions: PagesFunction = async () => corsPreflight();

export const onRequestPost: PagesFunction<{
  GROQ_API_KEY?: string;
}> = async ({ request, env }) => {
  let body: { query?: unknown };
  try {
    body = await request.json();
  } catch {
    return jsonResponse({ detail: "Invalid JSON body" }, 400);
  }
  const query = sanitizeQuery(body.query);
  if (!query) {
    return jsonResponse(
      { detail: "Query must be 1-1000 characters" },
      400,
    );
  }

  const { intent, weights } = classifyIntent(query);
  const apiKey = resolveGroqKey(request, env);

  if (apiKey) {
    try {
      const content = await callGroq({
        apiKey,
        model: "llama-3.1-8b-instant",
        temperature: 0.3,
        maxTokens: 300,
        messages: [
          {
            role: "system",
            content:
              "You are a search query optimization assistant. Always respond with valid JSON only.",
          },
          { role: "user", content: buildOptimizePrompt(query, intent) },
        ],
      });
      const parsed = extractJson(content);
      if (parsed) {
        return jsonResponse({
          github_query: String(parsed.github_query ?? query),
          huggingface_query: String(parsed.huggingface_query ?? query),
          reddit_query: String(parsed.reddit_query ?? query),
          intent,
          source_weights: weights,
          reasoning: String(parsed.reasoning ?? "Generated by Groq"),
        } satisfies OptimizeResponse);
      }
    } catch (e) {
      console.warn("Groq optimize-queries failed:", (e as Error).message);
    }
  }

  // Rule-based fallback preserves functionality when no key is configured
  // or Groq is unreachable.
  const year = new Date().getFullYear();
  const fallback: OptimizeResponse = {
    github_query: `${query} ${year}`.trim(),
    huggingface_query: `${query} ${year} latest`.trim(),
    reddit_query: `${query} ${year} best recommendation`.trim(),
    intent,
    source_weights: weights,
    reasoning: `Rule-based fallback (no AI available)`,
  };
  return jsonResponse(fallback);
};

// ---------------------------------------------------------------------------
// Intent classification — mirrors ai_logic.classify_query_intent.
// ---------------------------------------------------------------------------

type Intent =
  | "project_search"
  | "how_to"
  | "recommendation"
  | "comparison"
  | "troubleshooting"
  | "model_search"
  | "general";

const INTENT_PATTERNS: Record<Exclude<Intent, "general">, RegExp[]> = {
  project_search: [
    /\b(project|repo|repository|code|implementation|example|template|boilerplate)\b/i,
    /\b(github|clone|fork|open[- ]source)\b/i,
  ],
  how_to: [
    /\bhow (to|do|can)\b/i,
    /\b(guide|tutorial|steps|learn|build|create|setup)\b/i,
  ],
  recommendation: [
    /\b(best|top|recommend|suggestion|should i|which|better|vs)\b/i,
  ],
  comparison: [/\bvs\.?\b|\bversus\b/i, /\b(compare|comparison|difference)\b/i],
  troubleshooting: [
    /\b(error|issue|problem|bug|fix|broken|not working|help|solve)\b/i,
  ],
  model_search: [
    /\b(model|llm|transformer|neural network|ai model|ml model)\b/i,
    /\b(gpt|bert|llama|mistral|stable diffusion|clip)\b/i,
    /\b(hugging ?face|hf|pretrained)\b/i,
  ],
};

const INTENT_WEIGHTS: Record<Intent, Record<string, number>> = {
  project_search: { github: 0.7, reddit: 0.2, huggingface: 0.1 },
  how_to: { reddit: 0.6, github: 0.3, huggingface: 0.1 },
  recommendation: { reddit: 0.6, github: 0.25, huggingface: 0.15 },
  comparison: { reddit: 0.5, github: 0.3, huggingface: 0.2 },
  troubleshooting: { reddit: 0.7, github: 0.2, huggingface: 0.1 },
  model_search: { huggingface: 0.7, github: 0.2, reddit: 0.1 },
  general: { github: 0.4, reddit: 0.4, huggingface: 0.2 },
};

function classifyIntent(
  query: string,
): { intent: Intent; weights: Record<string, number> } {
  let best: Intent = "general";
  let bestScore = 0;
  for (const [intent, patterns] of Object.entries(INTENT_PATTERNS) as Array<
    [Exclude<Intent, "general">, RegExp[]]
  >) {
    const score = patterns.reduce(
      (acc, p) => acc + (p.test(query) ? 1 : 0),
      0,
    );
    if (score > bestScore) {
      bestScore = score;
      best = intent;
    }
  }
  return { intent: best, weights: INTENT_WEIGHTS[best] };
}

function buildOptimizePrompt(query: string, intent: Intent): string {
  const year = new Date().getFullYear();
  const month = new Date().toLocaleString("en-US", {
    month: "long",
    year: "numeric",
  });
  const guidance: Record<Intent, string> = {
    project_search:
      "Focus on finding concrete implementations and code examples. Prioritize GitHub.",
    how_to:
      "Focus on tutorials, guides, and discussions. Prioritize Reddit and GitHub examples.",
    recommendation:
      "Focus on community opinions and comparisons. Prioritize Reddit.",
    comparison:
      "Focus on detailed comparisons and benchmarks. Balance Reddit and GitHub.",
    troubleshooting:
      "Focus on solutions and discussions. Prioritize Reddit.",
    model_search:
      "Focus on AI models and pretrained weights. Prioritize HuggingFace.",
    general: "Balance all sources equally.",
  };
  return `You are a search optimization expert focused on finding THE MOST RECENT information. Today is ${month}.

USER'S QUERY: "${query}"
DETECTED INTENT: ${intent}
STRATEGY: ${guidance[intent]}

Generate search queries optimized for:
1. GitHub — exact technical terms, primary libraries/frameworks. MUST include "${year}" or "recent" or "latest".
2. Hugging Face — specific model types, task names, architecture names. MUST include "${year}" or "latest".
3. Reddit — recent discussions. MUST include "${year}" or "recent" plus keywords like "best", "recommendation".

CRITICAL RULES:
- ALWAYS include "${year}" OR "recent" OR "latest" in EVERY query
- Use exact technical terminology
- Keep each query under 60 characters

Respond ONLY in this exact JSON format:
{
    "github_query": "your github query",
    "huggingface_query": "your huggingface query",
    "reddit_query": "your reddit query",
    "reasoning": "brief explanation"
}`;
}

function extractJson(text: string): Record<string, unknown> | null {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}
